version: "3"
services:
  user:
    build: .
    depends_on:
      - redis
    ports:
      - 4000:4000
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PORT=4000

  redis:
    image: redis
    read_only: true
    volumes:
      - redis:/data
volumes:
  redis: