version: "3"
services:
  user:
    build: .
    depends_on:
      - redis
    ports:
      - 4000:4000

  redis:
    image: redis
    read_only: true
    volumes:
      - redis:/data
volumes:
  redis: